services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt.home
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - ./data:/app/data
    environment:
      TZ: Europe/Berlin
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "traefik.enable=true"
      - "traefik.http.routers.zigbee2mqtt.entryPoints=websecure"
      - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.home.schndr.cloud`)"
      - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
networks:
  dockernet:
    external: true
