#!/bin/zsh
#        _ _
#   __ _| (_) __ _ ___  ___  ___
#  / _` | | |/ _` / __|/ _ \/ __|
# | (_| | | | (_| \__ \  __/\__ \
#  \__,_|_|_|\__,_|___/\___||___/


# Common
alias \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  ls="ls --color=auto --group-directories-first -Nhla" \
  mkd="mkdir -vp" \
  cp="cp -vi" \
  mv="mv -vi" \
  rm="rm -vI" \

# Apps
alias \
  nv="nvim" \
  g="git" \
  d="docker"

# Utilities
if [[ $UID -eq 0 ]]; then
  alias update="apt update; apt upgrade -y; apt autoremove -y; apt autoclean -y; zinit update --all"
else
  alias update="sudo apt update; sudo apt upgrade -y; sudo apt autoremove -y; sudo apt autoclean -y; zinit update --all"
fi
