---
#  __  __  ___ _____ ____
# |  \/  |/ _ \_   _|  _ \
# | |\/| | | | || | | | | |
# | |  | | |_| || | | |_| |
# |_|  |_|\___/ |_| |____/
# Defaults


motd: "  _   _      _ _        __        __         _     _ _ \n
  | | | | ___| | | ___   \\ \\      / /__  _ __| | __| | | \n
  | |_| |/ _ \\ | |/ _ \\   \\ \\ /\\ / / _ \\| '__| |/ _` | | \n
  |  _  |  __/ | | (_) |   \\ V  V / (_) | |  | | (_| |_| \n
  |_| |_|\\___|_|_|\\___/     \\_/\\_/ \\___/|_|  |_|\\__,_(_) \n
  \n"
