---
#  __  __  ___ _____ ____
# |  \/  |/ _ \_   _|  _ \
# | |\/| | | | || | | | | |
# | |  | | |_| || | | |_| |
# |_|  |_|\___/ |_| |____/
# Tasks


- name: Clear the static message of the day
  ansible.builtin.copy:
    content: ""
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Copy the motd scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/update-motd.d/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: '0755'
  with_fileglob:
    - "{{ inventory_hostname }}/motd/*"
  become: true
