services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin.home
    image: ghcr.io/jellyfin/jellyfin:latest
    restart: unless-stopped
    networks:
      - dockernet
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/movies:/data/movies
      - /mnt/series:/data/series
    environment:
      TZ: Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entryPoints=websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.home.schndr.cloud`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
networks:
  dockernet:
    external: true
