- id: '1724725622792'
  alias: Aquarium
  description: Automation for the aquarium light.
  mode: single
  triggers:
    - trigger: time
      at: '12:00:00'
      id: aquarium_on
    - trigger: time
      at: '18:00:00'
      id: aquarium_off
  conditions: []
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: aquarium_on
          sequence:
            - action: switch.turn_on
              target:
                entity_id: switch.smart_plug_4
        - conditions:
            - condition: trigger
              id: aquarium_off
          sequence:
            - action: switch.turn_off
              target:
                entity_id: switch.smart_plug_4
