- id: '1724725622792'
  alias: Aquarium
  description: Automation for the aquarium light.
  mode: single
  triggers:
    - trigger: time
      at:
        - &light_on '12:00:00'
        - &light_off '18:00:00'
    - trigger: homeassistant
      event: start
  conditions: []
  actions:
    - if:
        - condition: time
          after: *light_on
          before: *light_off
      then:
        - action: switch.turn_on
          target:
            entity_id: switch.smart_plug_4
      else:
        - action: switch.turn_off
          target:
            entity_id: switch.smart_plug_4
