- id: styrbar_2
  alias: Styrbar 2
  description: Automation for the IKEA Styrbar remote control.
  mode: queued
  triggers:
    # Trigger - On
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: 'on'
      id: styrbar_2_on
    # Trigger - Brightness move up
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: brightness_move_up
      id: styrbar_2_brightness_move_up
    # Trigger - Off
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: 'off'
      id: styrbar_2_off
    # Trigger - Brightness move down
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: brightness_move_down
      id: styrbar_2_brightness_move_down
    # Trigger - Arrow left click
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: arrow_left_click
      id: styrbar_2_arrow_left_click
    # Trigger - Arrow left hold
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: arrow_left_hold
      id: styrbar_2_arrow_left_hold
    # Trigger - Arrow right click
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: arrow_right_click
      id: styrbar_2_arrow_right_click
    # Trigger - Arrow right hold
    - trigger: mqtt
      topic: "zigbee2mqtt/Styrbar 2"
      value_template: "{{ value_json.action }}"
      payload: arrow_right_hold
      id: styrbar_2_arrow_right_hold
  conditions: []
  actions:
    - choose:
        # Action - On
        - conditions:
            - condition: trigger
              id: styrbar_2_on
          sequence:
            - action: script.light_toggle
              data:
                entity_id:
                  - light.hue_color_lamp_1
                  - light.hue_color_lamp_2
                profile: bright
        # Action - Brightness move up
        - conditions:
            - condition: trigger
              id: styrbar_2_brightness_move_up
          sequence:
            - action: light.turn_on
              target:
                entity_id:
                  - light.hue_color_lamp_1
                  - light.hue_color_lamp_2
              data:
                profile: night
        # Action - Off
        - conditions:
            - condition: trigger
              id: styrbar_2_off
          sequence:
            - action: script.light_toggle
              data:
                entity_id: light.hue_color_lamp_3
                profile: bright
        # Action - Brightness move down
        - conditions:
            - condition: trigger
              id: styrbar_2_brightness_move_down
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.hue_color_lamp_3
              data:
                profile: night
        # Action - Arrow left click
        - conditions:
            - condition: trigger
              id: styrbar_2_arrow_left_click
          sequence:
            - action: script.light_toggle
              data:
                entity_id: light.hue_play_lightbar_1
                profile: bright
        # Action - Arrow left hold
        - conditions:
            - condition: trigger
              id: styrbar_2_arrow_left_hold
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.hue_play_lightbar_1
              data:
                profile: night
        # Action - Arrow right click
        - conditions:
            - condition: trigger
              id: styrbar_2_arrow_right_click
          sequence:
            - action: script.light_toggle
              data:
                entity_id: light.hue_luster_1
                profile: bright
        # Action - Arrow right hold
        - conditions:
            - condition: trigger
              id: styrbar_2_arrow_right_hold
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.hue_luster_1
              data:
                profile: night
