- id: styrbar_1
  alias: Styrbar 1
  description: Automation for the IKEA Styrbar remote control.
  mode: single
  triggers:
    # Trigger - On
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: 'on'
      id: styrbar_1_on
    # Trigger - Brightness move up
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: brightness_move_up
      id: styrbar_1_brightness_move_up
    # Trigger - Off
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: 'off'
      id: styrbar_1_off
    # Trigger - Brightness move down
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: brightness_move_down
      id: styrbar_1_brightness_move_down
    # Trigger - Arrow left click
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: arrow_left_click
      id: styrbar_1_arrow_left_click
    # Trigger - Arrow left hold
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: arrow_left_hold
      id: styrbar_1_arrow_left_hold
    # Trigger - Arrow right click
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: arrow_right_click
      id: styrbar_1_arrow_right_click
    # Trigger - Arrow right hold
    - trigger: device
      device_id: f4eb5bb5c6fcb2a4af35e1794b9486b8
      domain: mqtt
      type: action
      subtype: arrow_right_hold
      id: styrbar_1_arrow_right_hold
  conditions: []
  actions:
    - choose:
        # Action - On
        - conditions:
            - condition: trigger
              id: styrbar_1_on
          sequence:
            - action: >
                {% if is_state('light.hue_color_lamp_4', 'on') %}
                  light.turn_off
                {% else %}
                  script.light_bright
                {% endif %}
              target:
                entity_id: light.hue_color_lamp_4
        # Action - Brightness move up
        - conditions:
            - condition: trigger
              id: styrbar_1_brightness_move_up
          sequence:
            - action: script.light_night
              target:
                entity_id: light.hue_color_lamp_4
        # Action - Off
        - conditions:
            - condition: trigger
              id: styrbar_1_off
          sequence:
            - action: >
                {% if is_state('light.hue_luster_2', 'on')
                   or is_state('light.hue_luster_3', 'on')
                   or is_state('light.hue_luster_4', 'on')
                   or is_state('light.hue_go_1', 'on') %}
                  light.turn_off
                {% else %}
                  script.light_bright
                {% endif %}
              target:
                entity_id:
                  - light.hue_luster_2
                  - light.hue_luster_3
                  - light.hue_luster_4
                  - light.hue_go_1
        # Action - Brightness move down
        - conditions:
            - condition: trigger
              id: styrbar_1_brightness_move_down
          sequence:
            - action: script.light_night
              target:
                entity_id:
                  - light.hue_luster_2
                  - light.hue_luster_3
                  - light.hue_luster_4
                  - light.hue_go_1
        # Action - Arrow left click
        - conditions:
            - condition: trigger
              id: styrbar_1_arrow_left_click
          sequence:
            - action: >
                {% if is_state('cover.shelly_2pm_gen4_schlafzimmer', 'opening')
                   or is_state('cover.shelly_2pm_gen4_schlafzimmer', 'closing') %}
                  cover.stop_cover
                {% else %}
                  cover.open_cover
                {% endif %}
              target:
                entity_id: cover.shelly_2pm_gen4_schlafzimmer
        # Action - Arrow left hold
        - conditions:
            - condition: trigger
              id: styrbar_1_arrow_left_hold
          sequence:
        # Action - Arrow right click
        - conditions:
            - condition: trigger
              id: styrbar_1_arrow_right_click
          sequence:
            - action: >
                {% if is_state('cover.shelly_2pm_gen4_schlafzimmer', 'opening')
                   or is_state('cover.shelly_2pm_gen4_schlafzimmer', 'closing') %}
                  cover.stop_cover
                {% else %}
                  cover.close_cover
                {% endif %}
              target:
                entity_id: cover.shelly_2pm_gen4_schlafzimmer
        # Action - Arrow right hold
        - conditions:
            - condition: trigger
              id: styrbar_1_arrow_right_hold
          sequence:
