---
#  ____
# |  _ \ _ __ _____  ___ __ ___   _____  __  _ __ ___ _ __ ___   _____   _____   _ __   __ _  __ _
# | |_) | '__/ _ \ \/ / '_ ` _ \ / _ \ \/ / | '__/ _ \ '_ ` _ \ / _ \ \ / / _ \ | '_ \ / _` |/ _` |
# |  __/| | | (_) >  <| | | | | | (_) >  <  | | |  __/ | | | | | (_) \ V /  __/ | | | | (_| | (_| |
# |_|   |_|  \___/_/\_\_| |_| |_|\___/_/\_\ |_|  \___|_| |_| |_|\___/ \_/ \___| |_| |_|\__,_|\__, |
#                                                                                            |___/
# Handlers


- name: Restart the Proxmox proxy service
  ansible.builtin.service:
    name: "{{ 'pveproxy' if proxmox_ve.stat.exists else 'proxmox-backup-proxy' }}"
    state: restarted
