---
#  ____             _
# |  _ \  ___   ___| | _____ _ __
# | | | |/ _ \ / __| |/ / _ \ '__|
# | |_| | (_) | (__|   <  __/ |
# |____/ \___/ \___|_|\_\___|_|
# Tasks


- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: "{{ docker_gpg_key_dest }}"
    mode: '0644'
    force: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_repo }}"
    filename: docker
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure default Docker network exists
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    driver: bridge
    state: present
  when: docker_create_network
