---
motd: "   ____            __ _ \n
   / ___|_ __ __ _ / _| |_ _   _ \n
  | |   | '__/ _` | |_| __| | | | \n
  | |___| | | (_| |  _| |_| |_| | \n
   \\____|_|  \\__,_|_|  \\__|\\__, | \n
                           |___/ \n
  \n"

packages:
  - name: qemu-guest-agent

containers:
  - name: crafty
