---
packages:
  - name: qemu-guest-agent
  - name: firmware-misc-nonfree
  - name: intel-gpu-tools
  - name: btop
  - name: curl
  - name: unzip

nfs_shares: "{{ lilith_nfs_shares }}"

containers: "{{ lilith_containers }}"
