---
#  _     _ _ _ _   _
# | |   (_) (_) |_| |__
# | |   | | | | __| '_ \
# | |___| | | | |_| | | |
# |_____|_|_|_|\__|_| |_|


motd: "  _     _ _ _ _   _ \n
  | |   (_) (_) |_| |__ \n
  | |   | | | | __|  _ \\ \n
  | |___| | | | |_| | | | \n
  |_____|_|_|_|\\__|_| |_| \n
  \n"

add_packages:
  - qemu-guest-agent
  - curl

nfs_shares: "{{ lilith_nfs_shares }}"

containers: "{{ lilith_containers }}"
