services:
  n8n:
    container_name: n8n
    hostname: n8n.home
    image: n8nio/n8n:latest
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - ./data:/home/node/.n8n
    environment:
      TZ: Europe/Berlin
      GENERIC_TIMEZONE: Europe/Berlin
      N8N_RUNNERS_ENABLED: true
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_DIAGNOSTICS_CONFIG_FRONTEND:
      N8N_DIAGNOSTICS_CONFIG_BACKEND:
      EXTERNAL_FRONTEND_HOOKS_URLS:
      DB_SQLITE_POOL_SIZE: 5
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entryPoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.home.schndr.cloud`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
networks:
  dockernet:
    external: true
