services:
  n8n:
    container_name: n8n
    image: n8nio/n8n
    restart: unless-stopped
    hostname: n8n.home
    networks:
      - dockernet
    user: "0"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      TZ: Europe/Berlin
      GENERIC_TIMEZONE: Europe/Berlin
      QUEUE_HEALTH_CHECK_ACTIVE: true
      N8N_METRICS: true
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
      N8N_TEMPLATES_ENABLED: false
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_DIAGNOSTICS_CONFIG_FRONTEND:
      N8N_DIAGNOSTICS_CONFIG_BACKEND:
      EXTERNAL_FRONTEND_HOOKS_URLS:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entryPoints=websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.home.schndr.cloud`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
networks:
  dockernet:
    external: true
