services:
  authentik:
    container_name: authentik
    hostname: authentik.home
    image: ghcr.io/goauthentik/server:latest
    depends_on:
      - authentik-postgres
      - authentik-redis
    restart: unless-stopped
    command: server
    networks:
      - dockernet
    user: "0"
    volumes:
      - ./media:/media
      - ./templates:/templates
    environment:
      TZ: Europe/Berlin
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: true
      AUTHENTIK_DISABLE_UPDATE_CHECK: true
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_EMAIL__HOST: postfix
      AUTHENTIK_EMAIL__PORT: 25
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.entryPoints=websecure"
      - "traefik.http.routers.authentik.rule=Host(`authentik.home.schndr.cloud`)"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
  authentik-worker:
    container_name: authentik-worker
    hostname: authentik-worker.home
    image: ghcr.io/goauthentik/server:latest
    depends_on:
      - authentik-postgres
      - authentik-redis
    restart: unless-stopped
    command: worker
    networks:
      - dockernet
    user: "0"
    volumes:
      - ./media:/media
      - ./templates:/templates
      - ./certs:/certs
    environment:
      TZ: Europe/Berlin
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: true
      AUTHENTIK_DISABLE_UPDATE_CHECK: true
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_EMAIL__HOST: postfix
      AUTHENTIK_EMAIL__PORT: 25
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL__USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL__PASSWORD}
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL__FROM}
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
  authentik-redis:
    container_name: authentik-redis
    hostname: authentik-redis.home
    image: redis:latest
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - ./redis:/data
    environment:
      TZ: Europe/Berlin
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
  authentik-postgres:
    container_name: authentik-postgres
    hostname: authentik-postgres.home
    image: postgres:18
    restart: unless-stopped
    networks:
      - dockernet
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
networks:
  dockernet:
    external: true
