---
#  _   _ _____ ____    ____  _
# | \ | |  ___/ ___|  / ___|| |__   __ _ _ __ ___  ___
# |  \| | |_  \___ \  \___ \| '_ \ / _` | '__/ _ \/ __|
# | |\  |  _|  ___) |  ___) | | | | (_| | | |  __/\__ \
# |_| \_|_|   |____/  |____/|_| |_|\__,_|_|  \___||___/
# Defaults


nfs_shares: []
