---
#  ____
# |  _ \ _ __ _____  ___ __ ___   _____  __  _ __ ___ _ __ ___   _____   _____   _ __   __ _  __ _
# | |_) | '__/ _ \ \/ / '_ ` _ \ / _ \ \/ / | '__/ _ \ '_ ` _ \ / _ \ \ / / _ \ | '_ \ / _` |/ _` |
# |  __/| | | (_) >  <| | | | | | (_) >  <  | | |  __/ | | | | | (_) \ V /  __/ | | | | (_| | (_| |
# |_|   |_|  \___/_/\_\_| |_| |_|\___/_/\_\ |_|  \___|_| |_| |_|\___/ \_/ \___| |_| |_|\__,_|\__, |
#                                                                                            |___/
# Tasks


- name: Check if the system is Proxmox VE
  ansible.builtin.stat:
    path: /etc/pve
  register: proxmox_ve

- name: Remove Proxmox subscription nag message
  ansible.builtin.lineinfile:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: '^(\s*checked_command: function ?\(orig_cmd\) \{)\s*$'
    line: '\1 orig_cmd(); return; //nonag'
    backrefs: true
  notify: Restart the Proxmox proxy service
