---
#  ____                             ____ ____  _   _
# / ___|  ___  ___ _   _ _ __ ___  / ___/ ___|| | | |
# \___ \ / _ \/ __| | | | '__/ _ \ \___ \___ \| |_| |
#  ___) |  __/ (__| |_| | | |  __/  ___) |__) |  _  |
# |____/ \___|\___|\__,_|_|  \___| |____/____/|_| |_|
# Handlers


- name: Restart sshd service
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
