services:
  pihole:
    container_name: pi-hole
    hostname: pi-hole.home
    image: pihole/pihole:latest
    restart: unless-stopped
    networks:
      - dockernet
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./data:/etc/pihole
      - ./dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: Europe/Berlin
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      FTLCONF_dns_listeningMode: 'all'
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entryPoints=websecure"
      - "traefik.http.routers.pihole.rule=Host(`pihole.home.schndr.cloud`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
networks:
  dockernet:
    external: true
